name: keychat_ecash
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.0.0"
resolution: workspace

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  keychat: ^1.0.0
  keychat_rust_ffi_plugin: 1.0.0
  ndk: ^0.7.0
