name: keychat_ecash
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.0.0"
resolution: workspace

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  timer_builder: ^2.0.0
  keychat: ^1.36.5
  keychat_rust_ffi_plugin: 1.0.0
  flutter_easyloading: ^3.0.5
  easy_debounce: ^2.0.3
  get: ^4.7.2
  settings_ui: ^2.0.2
  carousel_slider: ^5.1.1
  intl: ^0.20.2
  dio: ^5.8.0+1
  url_launcher: ^6.3.1
  flutter_svg: ^2.2.0
  custom_refresh_indicator: ^4.0.1
